### ISSUE TITLE
FooterClass

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#10]
Створення таких класів це не реактовський підхід. Можна отримати багато небажаних побічних ефектів та погану отпимізацію

Більш правильним підходом буде
1. `linksListObjectsFooter` - звичайний масив з обʼєктами
2. в `UnorderedList` додати пропс `renderItem` в який можна передати функцію яка рендерить елементи

В результаті вийде приблизно так
```
<UnorderedList list={linksListObjectsFooter} renderItem={({href, className}) => (
    <FooterItem className={className} href={href}> 
)}/>
```

```
<ul className={className}>
    {list.map(item=> <li key={item.id}> { renderItem(item) }</li>)}
</ul>
```

**Comment by SurkovKostiantyn** [comment]
in progress
