### ISSUE TITLE
nanoid

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#13]
`<li key={nanoid()}>`
Використовувати nanoid одразу в key неможна. Для оптимізації це ще гірше ніж index. При кожному перерендері key буде змінюватись
Але можно використовувати nanoid під час створення обʼєкту

```
const linksListObjectsNav = [
  {
    id: 0, href: 'index.html', className: 'navbar-menu-item hoverable active', innerHTML: 'Home', key: nanoid()
  },
  {
    id: 1, href: 'news.html', className: 'navbar-menu-item hoverable', innerHTML: 'News', key: nanoid()
  }
];
```

Або використовувати id в якості key

**Comment by SurkovKostiantyn** [comment]
+
