### ISSUE TITLE
PropTypes 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#14]
`list` в `UnorderedList` не обовʼязково прописувати повністю весь. Можно лише ті елементи які будуть використовуватись всередині компонента

```
 list: PropTypes.arrayOf(PropTypes.shape({
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
  })).isRequired,
```

наприклад так, якщо id буде використовуватись як key

**Comment by SurkovKostiantyn** [comment]
+
