### ISSUE TITLE
onImageError

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#17]
`e.target.src = defaultImage;`
Оновлення DOM в обхід реакту. Додай в стейт змінну, щось типу `isError` або `isDefault` а в src додай логіку відповідно до цієї змінной

```
src={src || defaultImage}
...
src: PropTypes.string.isRequired
```

Якщо `src` обовʼязкове значення, то йому не потрібне `defaultImage`. А якне не обовʼязкове, то краще додай `defaultImage` в `Image.defaultProps`

**Comment by SurkovKostiantyn** [comment]
src={isLoaded ? src : defaultImage}
