### ISSUE TITLE
React.useRef < any > null

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#19]
```
this.dragItem = React.useRef < any > null;
this.dragOverItem = React.useRef < any > null;
```

Цікаво, навіть не думав що це запуститься 😄 

1. useRef - це хук, хуки для функціональних компонентів
2. < any > - це TypeScript
3. any в бідь-якому випадку використовувати не можна

Краще користуйся `React.createRef`
`this.dragItem = React.createRef();`

**Comment by DmitriiMelnikOnix** [comment]
Хоча, передивився код
Якщо потрібно зберегти щось в ref потрібно зберігати в `this.refName.current  = 10`.
Тобі не потрібен `React.createRef`, ти рефом не користуєшься
Можешь просто створити змінні в конструкторі 

```
this.dragItem = null;
this.dragOverItem = null;
```

І все буде працювати так само

**Comment by SurkovKostiantyn** [comment]
this.dragItem = null;
this.dragOverItem = null;

+++
