### ISSUE TITLE
funcOnDragEnd

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#22]
```
setTimeout(() => {
  this.setState({ isActive: null });
}, 100);
```
На скільки я зрозумів то setTimeout тут для того щоб анімація вигладала краще. 
Спробуй використати css для цього
Думаю щось типу `animation-delay` може допомогти

**Comment by SurkovKostiantyn** [comment]
Так, для анімації. setState прибрав, і так норм виглядає. ТО для експериментів було
