### ISSUE TITLE
DragAndDrop 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#26]
Цікаве спостереження, якщо перенести останній елемент в початок то анімація спрацює для всіх елементів, а якщо перший в кінець, то лице для того який перенесли

**Comment by SurkovKostiantyn** [comment]
з цим потрібно щось робити?
ось цей код
`  funcSwitchItems = (draggedItem, staticItem) => {
    const { list } = this.state;
    const dragItemIndex = list.findIndex((item) => item.id === draggedItem); // который тащим
    const dragOverItemIndex = list.findIndex((item) => item.id === staticItem); // над которым висит
    const newList = [...list];
    newList.splice(dragItemIndex, 1);
    newList.splice(dragOverItemIndex, 0, list[dragItemIndex]);
    this.setState({ list: newList });
  };`

**Comment by DmitriiMelnikOnix** [comment]
Спробував розібратись, так нічого і не знайшов, але якщо прибрати анімацію з `img` то виглядає кращ

**Comment by SurkovKostiantyn** [comment]
прибрав анімацію
