### ISSUE TITLE
Оновлення стейту 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#27]
```
const { list, idSelected } = this.state;
const idSelectNext = (idSelected + 1) % list.length;
this.setState(
  { idSelected: idSelectNext }
);
```

Якщо нове значення залежить від минулого - краще використати функцію для оновлення
Якщо в якомусь випадку маже одночасно додасться або видалиться елемент з list і разом з цим буде викликана handleKeyUp то в this.state буде ще старий список, а в прикладі нижче вже новий

```
this.setState(({list, idSelected}) => ({ 
   idSelected: (idSelected + 1) % list.length; 
}));
```

В такому прикладі як би не змінювались `list` та `idSelected` в функції вони будуть найсвіжіші

**Comment by SurkovKostiantyn** [comment]
виправив
