### ISSUE TITLE
bind

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#30]
`this.toggleTheme = this.toggleTheme.bind(this);`
Якщо створювати функцію за допомогою стрілочної функції, то додавати цей рядок не потрібно

```javascript
toggleTheme = () => {
  this.setState((prevState) => ({
    theme: !prevState.theme
  }));
}
```
Це повʼязано з тим що звичайні функції мають свій `this`, а стрілочні ні

**Comment by SurkovKostiantyn** [comment]
+
