### ISSUE TITLE
Props в state

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#7]
```
constructor(props) {
    super(props);
    this.state = {
        src: props.src,
        className: this.props.className,
        alt: this.props.alt
    }
}
```

Зберігати пропс в стейт можна якщо тобі потрібно початкове значення пропсу, або ти плануєшь оновлювати цей пропс вручну
В цьому випадку виходить що в стейт збережуться лише ті значення пропсу що були перед монтуванням компонента. І змінюватись вони не будуть

Краще прибрати це збереження в стейт і просто використовувати пропс 

```
render(){
    const {src, className, alt } = this.props;
    return(
        <img src={src} className={className} alt={alt}/>
    )
}
```

**Comment by DmitriiMelnikOnix** [comment]
Те ж саме і в `JustALittleTag.jsx`

**Comment by DmitriiMelnikOnix** [comment]
і в `Link` і не тільки

**Comment by SurkovKostiantyn** [comment]
done
