### ISSUE TITLE
Мутація в `funcSortByDateASCCustom`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [SurkovKostiantyn/react_onix_academy#9]
1. `let arr = this.state.list;` краще записати через десктруктуризацію `let { list: arr } = this.state;`
2. Ти змінюєшь початковий масив `arr` який зберігаеється в стейті. Краще скпріювати його перед сортуванням

**Comment by DmitriiMelnikOnix** [comment]
І в `funcAddElement` 
Замість `push` можна використати 
`const newArr = [...arr, {title: 'title', date: 'date'}]`

**Comment by SurkovKostiantyn** [comment]
+
